"""Native backend — drive a compiled ``libcib`` shared library via ctypes.

This backend ships **no Julia source**: the engine is a PackageCompiler-built
shared library (machine code + bundled Julia runtime). The library exposes a
small C ABI (see ``capi/src/CIBCApi.jl``) of JSON-in / JSON-out functions over
integer model handles; this module marshals JSON across ``ctypes`` and returns
native Python values.

Finding the library, in order:
  1. ``CIB_NATIVE_LIB`` — explicit path to the library file, or its bundle dir.
  2. bundled in the wheel: ``crossimpactbalances/_libcib/lib/libcib.*``.
  3. in-repo build output: ``build/cib-lib/lib/libcib.*``.

Threads are off by default (safe under a foreign runtime). Set
``CIB_NATIVE_THREADS`` (e.g. ``auto`` or ``4``) before first use to pass ``-t``
to the embedded Julia at init.
"""

from __future__ import annotations

import atexit
import ctypes
import glob
import json
import os
import sys
import threading
from typing import Any, Dict, List, Optional

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_HERE, "..", ".."))


class CIBNativeError(RuntimeError):
    """An error returned by the native engine, or a failure to load it."""


def _lib_filename() -> str:
    if sys.platform.startswith("win"):
        return "libcib.dll"
    if sys.platform == "darwin":
        return "libcib.dylib"
    return "libcib.so"


def _candidate_paths() -> List[str]:
    fname = _lib_filename()
    cands: List[str] = []
    env = os.environ.get("CIB_NATIVE_LIB")
    if env:
        # Accept either the library file itself or a bundle directory.
        if os.path.isfile(env):
            cands.append(env)
        else:
            cands.append(os.path.join(env, "lib", fname))
            cands.append(os.path.join(env, fname))
    cands.append(os.path.join(_HERE, "_libcib", "lib", fname))
    cands.append(os.path.join(_REPO_ROOT, "build", "cib-lib", "lib", fname))
    # Any-name fallback (versioned .so files, etc.)
    for base in (os.path.join(_HERE, "_libcib", "lib"),
                 os.path.join(_REPO_ROOT, "build", "cib-lib", "lib")):
        cands.extend(sorted(glob.glob(os.path.join(base, "libcib*"))))
    return cands


def _find_library() -> str:
    tried = _candidate_paths()
    for path in tried:
        if os.path.isfile(path):
            return path
    raise CIBNativeError(
        "Could not locate the compiled CIB library (libcib). Build it with\n"
        "    julia --project=build build/build_library.jl\n"
        "or set CIB_NATIVE_LIB to the library file or its bundle directory.\n"
        "Looked in:\n  " + "\n  ".join(tried))


class _NativeLib:
    """Loads the shared library once and wraps its C ABI."""

    _instance: Optional["_NativeLib"] = None
    _lock = threading.Lock()

    def __init__(self, path: str):
        self.path = path
        self._lib = ctypes.CDLL(path)
        self._configure()
        self._init_runtime()

    @classmethod
    def get(cls) -> "_NativeLib":
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = cls(_find_library())
        return cls._instance

    def _configure(self):
        L = self._lib
        c_char_p, c_int, c_void_p = ctypes.c_char_p, ctypes.c_int, ctypes.c_void_p
        # Runtime lifecycle (generated by PackageCompiler).
        L.init_julia.argtypes = [c_int, ctypes.POINTER(c_char_p)]
        L.init_julia.restype = None
        L.shutdown_julia.argtypes = [c_int]
        L.shutdown_julia.restype = None
        # cib_* surface. String returns come back as raw pointers (c_void_p) so
        # we can free them; c_char_p would copy and leak the original.
        sigs = {
            "cib_load": ([c_char_p], c_void_p),
            "cib_free": ([c_int], None),
            "cib_copy": ([c_int], c_void_p),
            "cib_consistent": ([c_int, c_char_p], c_void_p),
            "cib_basins": ([c_int, c_char_p], c_void_p),
            "cib_impact_balance": ([c_int, c_char_p], c_void_p),
            "cib_signature": ([c_int, c_char_p], c_void_p),
            "cib_inv_signature": ([c_int, c_char_p], c_void_p),
            "cib_succession": ([c_int, c_char_p], c_void_p),
            "cib_set_impact": ([c_int, c_char_p], c_void_p),
            "cib_get_impact": ([c_int, c_char_p], c_void_p),
            "cib_matrix": ([c_int], c_void_p),
            "cib_free_string": ([c_void_p], None),
        }
        for name, (argtypes, restype) in sigs.items():
            fn = getattr(L, name)
            fn.argtypes = argtypes
            fn.restype = restype

    def _init_runtime(self):
        argv_list = [b"libcib"]
        threads = os.environ.get("CIB_NATIVE_THREADS")
        if threads:
            argv_list += [b"-t", str(threads).encode()]
        arr = (ctypes.c_char_p * len(argv_list))(*argv_list)
        self._lib.init_julia(len(argv_list), arr)
        atexit.register(self._shutdown)

    def _shutdown(self):
        try:
            self._lib.shutdown_julia(0)
        except Exception:
            pass

    # -- JSON call helpers --------------------------------------------------

    def _take(self, ptr) -> Dict[str, Any]:
        """Decode a returned JSON pointer, free it, and check for errors."""
        if not ptr:
            raise CIBNativeError("native call returned NULL")
        raw = ctypes.cast(ptr, ctypes.c_char_p).value
        self._lib.cib_free_string(ptr)
        data = json.loads(raw.decode("utf-8"))
        if data.get("ok") is False:
            raise CIBNativeError(data.get("error", "unknown native error"))
        return data

    def load(self, path: str) -> Dict[str, Any]:
        return self._take(self._lib.cib_load(str(path).encode("utf-8")))

    def call(self, name: str, handle: int, payload: Any = None) -> Dict[str, Any]:
        fn = getattr(self._lib, name)
        if payload is None and name in ("cib_matrix",):
            return self._take(fn(ctypes.c_int(handle)))
        body = json.dumps(payload if payload is not None else {}).encode("utf-8")
        return self._take(fn(ctypes.c_int(handle), body))

    def free(self, handle: int):
        self._lib.cib_free(ctypes.c_int(handle))


class NativeBackend:
    """Index-based engine backend over the compiled library.

    Implements the same protocol as the juliacall backend, so :class:`Model`
    treats them interchangeably. All scenarios are length-``ndesc`` lists of
    0-based variant indices.
    """

    name = "native"

    def __init__(self, handle: int, structure: Dict[str, Any],
                 lib: Optional[_NativeLib] = None):
        self._lib = lib or _NativeLib.get()
        self._handle = handle
        self._structure = structure
        self._closed = False

    @classmethod
    def load(cls, path: str, **_ignored) -> "NativeBackend":
        lib = _NativeLib.get()
        d = lib.load(path)
        structure = {
            "descriptors": [str(x) for x in d["descriptors"]],
            "variants": {k: [str(v) for v in vs] for k, vs in d["variants"].items()},
            "n_descriptors": int(d["n_descriptors"]),
            # Past 2**53 the engine sends counts and signatures as decimal
            # strings, so a JSON consumer backed by doubles cannot round their
            # last digits away (see `_json_count` in capi/src/CIBCApi.jl).
            # Python's int() takes either form and is arbitrary-precision, so
            # a 10**24-scenario model arrives here exact.
            "n_scenarios": int(d["n_scenarios"]),
        }
        return cls(int(d["handle"]), structure, lib=lib)

    def structure(self) -> Dict[str, Any]:
        return self._structure

    def find_consistent(self, *, exhaustive=False, algorithm="auto",
                        ignore_cycles=True, rule="global", seed=None) -> List[List[int]]:
        opts = {"exhaustive": bool(exhaustive), "algorithm": algorithm,
                "ignore_cycles": bool(ignore_cycles), "rule": rule}
        if seed is not None:
            opts["seed"] = int(seed)
        d = self._lib.call("cib_consistent", self._handle, opts)
        return [[int(x) for x in u] for u in d["scenarios"]]

    def find_basins(self, *, rule="global"):
        d = self._lib.call("cib_basins", self._handle, {"rule": rule})
        fps = [[int(x) for x in u] for u in d["fixed_points"]]
        sizes = [int(x) for x in d["basin_sizes"]]
        return fps, sizes, int(d["cycle_count"]), int(d["total"])

    def impact_balance(self, u: List[int]) -> List[int]:
        d = self._lib.call("cib_impact_balance", self._handle, list(u))
        return [int(x) for x in d["ib"]]

    def succession(self, u: List[int], *, rule="global", max_steps=None):
        payload = {"scenario": list(u), "rule": rule}
        if max_steps is not None:
            payload["max_steps"] = int(max_steps)
        d = self._lib.call("cib_succession", self._handle, payload)
        steps = [[int(x) for x in s] for s in d["steps"]]
        return steps, int(d["cycle_length"])

    def signature(self, u: List[int]) -> int:
        return int(self._lib.call("cib_signature", self._handle, list(u))["signature"])

    def inv_signature(self, s: int) -> List[int]:
        # Send the decimal string past 2**53, mirroring the form cib_signature
        # emits: a bare JSON number that large overflows the engine's own
        # number parser, and that parse error would displace the C API's
        # explanation of why the inverse direction stops at Int64.
        s = int(s)
        d = self._lib.call("cib_inv_signature", self._handle,
                           s if abs(s) <= 2 ** 53 else str(s))
        return [int(x) for x in d["scenario"]]

    def set_impact(self, sd, sv, td, tv, value) -> int:
        d = self._lib.call("cib_set_impact", self._handle,
                           {"source": [int(sd), int(sv)],
                            "target": [int(td), int(tv)], "value": int(value)})
        return int(d["old"])

    def get_impact(self, sd, sv, td, tv) -> int:
        d = self._lib.call("cib_get_impact", self._handle,
                           {"source": [int(sd), int(sv)], "target": [int(td), int(tv)]})
        return int(d["value"])

    def matrix(self) -> List[List[int]]:
        d = self._lib.call("cib_matrix", self._handle)
        return [[int(x) for x in row] for row in d["matrix"]]

    def copy(self) -> "NativeBackend":
        d = self._lib.call("cib_copy", self._handle)
        return NativeBackend(int(d["handle"]), self._structure, lib=self._lib)

    def close(self):
        if not self._closed:
            try:
                self._lib.free(self._handle)
            finally:
                self._closed = True

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass
